/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amitkot_android_ndk_example_MainNDKActivity */

#ifndef _Included_example
#define _Included_example
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_amitkot_android_ndk_example_MainNDKActivity
 * Method:    messageFromNativeCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_amitkot_android_ndk_example_MainNDKActivity_messageFromNativeCode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}

#endif
#endif
